version: '3'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./db/mount:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/ -schemas=public -user=postgres -password=password -connectRetries=60 migrate
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - db

  base-api:
     build: ./base-api
     command: npm run start:dev
     volumes:
       - ./base-api/src:/base-api/src
     ports: 
       - 8000:8000
     depends_on:
       - db

  store:
     build: ./apps/store
     command: npm run dev
     volumes:
       - ./apps/store/src:/store/src
     ports: 
       - 3001:3001
     depends_on:
       - base-api